language: r

# Be strict when checking our package
warnings_are_errors: true

# Install development version of lme4, modified to allow a constant response
r_github_packages:
 - heogden/lme4@const_response
